### ISSUE TITLE
没演示地址，想问下，上传的图片是否支持拖拽排序和自定义“名称”。

### ISSUE THREAD

**Issue by xjdata** [liyunfang/yii2-upload-behavior#1]
如题，谢谢。

**Comment by pgyf** [comment]
@xjdata  这个不支持前台的效果
只支持后台自动上传生成多缩略图等
前台建议使用  https://github.com/kartik-v/yii2-widget-fileinput  阿三的控件支持拖拽   在readme中说过了
支持自定义名称 配置的时候参数generateNewName可以用function($file) $file就是UploadedFile上传实例
